# Generated by Django 5.0.6 on 2024-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_usuario',
            field=models.BooleanField(blank=True, default=False, verbose_name='manzaneros'),
        ),
    ]
