# Generated by Django 5.1.2 on 2024-11-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Administrador Status'),
        ),
    ]
