# Generated by Django 5.1.2 on 2024-11-20 01:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('persona', 'Persona Natural'), ('comercio', 'Comercio')], max_length=10)),
                ('tipo_p', models.CharField(blank=True, choices=[('V', 'V'), ('E', 'E')], max_length=1, null=True)),
                ('tipo_rif', models.CharField(blank=True, choices=[('G', 'G'), ('I', 'I')], max_length=1, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='La cédula debe tener al menos 8 dígitos.'), django.core.validators.MaxLengthValidator(10, message='La cédula debe tener como máximo 10 dígitos.'), django.core.validators.RegexValidator(message='La cédula debe contener solo números.', regex='^\\d+$')])),
                ('rif', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RIF debe contener solo números.', regex='^\\d+$')])),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener entre 7 y 11 números.', regex='^\\d{7,11}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_n', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=1)),
                ('cedula_identidad', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='La cédula debe tener al menos 8 dígitos.'), django.core.validators.MaxLengthValidator(10, message='La cédula debe tener como máximo 10 dígitos.'), django.core.validators.RegexValidator(message='La cédula debe contener solo números.', regex='^\\d+$')])),
                ('nombre', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El nombre debe contener solo letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('apellido', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El apellido debe contener solo letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(7, message='El teléfono debe tener al menos 7 dígitos.'), django.core.validators.MaxLengthValidator(11, message='El teléfono debe tener como máximo 11 dígitos.'), django.core.validators.RegexValidator(message='El teléfono debe contener solo números.', regex='^\\d+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_medicamento', models.CharField(choices=[('Genérico', 'Genérico'), ('Comercial', 'Comercial')], max_length=10)),
                ('tipo_farmac', models.CharField(choices=[('Tabletas', 'Tabletas'), ('Capsulas', 'Capsulas'), ('Jarabes', 'Jarabes'), ('Soluciones', 'Soluciones'), ('Gotas orales', 'Gotas orales'), ('Cremas', 'Cremas'), ('Inyectables', 'Inyectables'), ('Supositorios', 'Supositorios'), ('Otros', 'Otros')], max_length=20)),
                ('componentes', models.TextField()),
                ('concentracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medicamentos.destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_recepcion', models.DateField()),
                ('benefactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.benefactor')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('produccion_tanda', models.DateField()),
                ('vencimiento_tanda', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('benefactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.benefactor')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('benefactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.benefactor')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Medicamentos.entrega')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicamentos.medicamento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Medicamentos.registromedicamento')),
            ],
        ),
    ]
