# Generated by Django 5.1.2 on 2024-11-13 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='telefono',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener entre 7 y 11 números.', regex='^\\d{7,11}$')]),
        ),
    ]
