# Generated by Django 5.1.2 on 2024-11-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0002_registromedicamento_nombrecitolulu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromedicamento',
            old_name='fecha_registro',
            new_name='fecha_registro_medicamento',
        ),
    ]
